### ISSUE TITLE
Responsivity 

### ISSUE THREAD

**Issue by zurda** [fac-15/kash-portfolio#34]
A few things we noticed on mobile display: 

1. Border box around description breaks 
<img width="691" alt="screenshot 2018-11-02 at 10 28 10" src="https://user-images.githubusercontent.com/16784959/47911392-2f4b0200-de8d-11e8-9649-3afbb11b99b1.png">

2. Last two sections not full width: 
<img width="339" alt="screenshot 2018-11-02 at 10 27 46" src="https://user-images.githubusercontent.com/16784959/47911406-3b36c400-de8d-11e8-9ea9-e200ef3fad25.png">

3. Fonts a little too small on mobile display 

4. Would you consider adding a hover to links to make it more intuitive?

**Comment by tantsandras** [comment]
Yes we ran out of time haha! But I think we managed to fix some of it!
