### ISSUE TITLE
Accessibility Audit

### ISSUE THREAD

**Issue by Oliversw** [fac-15/kash-portfolio#38]
Just going to put all of the audit issues here to save some time! (don't worry, there's not many 😉 )
1. Links do not have a discernible name
- "Link text (and alternate text for images, when used as links) that is discernible, unique, and focusable improves the navigation experience for screen reader users."
- ```<a href="https://github.com/teenie-quaggard/teenie-quaggard.github.io" target="_blank" rel="noopener"> </a>``` is the only link that the audit seems to have a problem with. I tried to find out why it was only that link but it wasn't clear for me, so hopefully it's easier for you!
2. Elements Describe Contents Well
- "For elements do not have associated labels - Labels ensure that form controls are announced properly by assistive technologies, like screen readers."
- Just the text area: ```<textarea name="comment" form="usrform" placeholder="Enter text here.." class="field-long field-textarea"></textarea>``` Easy fix!
3. Colour contrast
- "Low-contrast text is difficult or impossible for many users to read"
- The audit has a problem with the contrast of the text and links in the team area. We all really like the fonts and the colours, but it seems that there needs to be a little more contrast
4. Tab order issues
- When tabbing through the page, everything worked until I got to Kristina's section. After making 'Github' the focus and pressing tab, the focus disappears for two tabs until coming back to Kristina's next link. Everything works after that though!

**Comment by HStewart23** [comment]
-text area labelling done 
-color contrast done

**Comment by HStewart23** [comment]
- added labels to sections
